LG_INSTANCE([[https://lg-antarctica-gateway.sess.dn42/]],[[Antarctica Gateway]])
LG_INSTANCE([[https://lg.bzip9.sess.dn42/]],[[Bzip 9]])
LG_INSTANCE([[https://lg.chronnection.sess.dn42/]],[[Chronnection]])
LG_INSTANCE([[https://lg.mazarino.sess.dn42/]],[[Mazarino]])
LG_INSTANCE([[https://lg.netzilla.sess.dn42/]],[[Netzilla]])
LG_INSTANCE([[https://lg.neonled.sess.dn42/]],[[NEON LED]])
LG_INSTANCE([[https://lg.touhou.sess.dn42/]],[[TouHou]])
LG_INSTANCE([[https://lg.glaciaxion.sess.dn42/]],[[Glaciaxion]])
LG_INSTANCE([[https://lg.hydrogen.sess.dn42/]],[[Hydrogen]])
LG_INSTANCE([[https://lg.alps.sess.dn42/]],[[Alps]])
